version: '3.1'
services:
  web:
    image: ortussolutions/commandbox:lucee5
    container_name: luceeweb
    ports:
     - "80:8080"
    volumes:
      - ./app:/app
    environment:
      BOX_SERVER_CFCONFIGFILE : .config.json
    networks:
      - custom-net
    depends_on:
      - appdb  
  appdb:
    #platform: linux/x86_64
    image: mysql
    container_name: appdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdata.sql:/docker-entrypoint-initdb.d/initdata.sql
    environment:
      MYSQL_ROOT_PASSWORD : changeme
      MYSQL_DATABASE : appdatabase
    networks:
      - custom-net

networks:
  custom-net: